fix: Fix compatibility with php 8.4 and newer ImageMagick library versions
Imagick/imagick pull request #704
Opened 2024-11-30 10:53 UTC by michalananapps

2024-12-05 17:50 UTC, calebdw commented
@michalananapps, 

Not sure if this is related to this PR or not, but I'm unable to install the latest imagick extension (with IM 6) in a PHP8.4 docker container:

```
#12 24.28 In /tmp/pear/temp/imagick/Imagick.stub.php:
#12 24.28 Imagick::newImage(): Parameter format has null default, but is not nullable
#12 24.29 make: *** [Makefile:191: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
#12 24.31 ERROR: `make INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuser8bmcdts2h2djeKWEFxQ/install-imagick-3.7.0" install' failed
#12 ERROR: process "/bin/sh -c pecl install imagick imap uv xdebug     && pecl install -o -f redis     && rm -rf /tmp/pear     && docker-php-ext-enable imagick imap redis" did not complete successfully: exit code: 1
```

because this is not explicitly nullable:
https://github.com/Imagick/imagick/blob/master/Imagick.stub.php#L1176

2024-12-05 19:13 UTC, michalananapps commented
> Not sure if this is related to this PR or not, but I'm unable to install the latest imagick extension (with IM 6) in a PHP8.4 docker container:

This PR is one of the fixes for compatibility with PHP 8.4, but it is not directly related to your issue. Your issue is related to the Imagick.stub.php file, which was fixed in the develop branch six months ago but has not yet been included in an official release. You are currently using the PECL official release, where this fix is not available yet. Commit with the fix: [Commit Link](https://github.com/Imagick/imagick/commit/6526e1ffd8811f3b0007ab38edc365e5c168514c).

You can install any development version of Imagick using `mlocati/php-extension-installer`. For example:  
```dockerfile
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/  
RUN install-php-extensions https://api.github.com/repos/michalananapps/imagick/tarball/cd0bc8f4269ee3845b2cc216f5555dc2a676712b  
```  
This command will install the version from the specified commit. However, you must ensure that you only install it from trusted sources. The example above uses the current commit of this PR's source branch. Use it at your own risk. 😊

2024-12-05 20:57 UTC, calebdw commented
Awesome, thanks for the info---I didn't know this tool existed!

It looks like PHP 8.4 support for imagick is built into the tool so you can just use:
```Dockerfile
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN install-php-extensions imagick
```

2025-01-23 14:02 UTC, parallels999 commented
ping @Danack

2025-01-30 12:46 UTC, Inscure commented
@Danack could you look at this PR? thank you

2025-02-28 22:44 UTC, bukka requested changes
Could you please split the CI (including `util/calculate_cflags.php`) and version check to two PR's? Please also remove the imagick.c changes as they are already merged. They are independent.

2025-02-28 22:44 UTC, bukka commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
Those replacements are already merged to develop so please remove them.

2025-03-01 18:34 UTC, michalananapps commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
@bukka First of all, I wanted to say that I'm really happy that you took care of this project :). As for the split, I can do it, but some of the changes related to CI require modifications that are part of the version check. I'll first submit a PR with the version check and then another one for CI with the newer PHP versions.

2025-03-01 18:39 UTC, bukka commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
Cool thanks. Of if it's easier, you can just split it to two commits and push force it here...

2025-03-01 18:40 UTC, bukka commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
Also please rebase on the latest develop - I pushed few commits to fix build.

2025-03-01 19:29 UTC, michalananapps commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
@bukka is there a plan to drop PHP5.4 and PHP5.6 support?

2025-03-01 20:06 UTC, michalananapps commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
@bukka 1st part: https://github.com/Imagick/imagick/pull/716

We can close this (#704).

2025-03-01 20:20 UTC, bukka commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
> @bukka is there a plan to drop PHP5.4 and PHP5.5 support?

Yeah I want to actually drop them and keep just 5.6 for the next release. Then I would like to drop PHP 5 support completely in the following release.

2025-03-01 21:13 UTC, onlime commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
very nice to hear you guys getting Imagick into shape again! But honestly, why not drop any EOL version, anything below PHP 8.1?

2025-03-01 21:31 UTC, bukka commented on imagick.c
> +						zend_str_tolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));
There are long term support commercial plans and some distros keep it longer so currently the oldest supported version that I'm aware of is 7.2 but think 7.0 and 7.1 don't really cost much extra in terms of maintanence so I don't really mind to keep those if they just work in pipeline. The 5.6 got some updates and dropping the support should be also done with clean up which would delay the next release so that's why I want to do it in the follow up version.

2025-03-02 10:53 UTC, bukka commented
#716 is merged so closing this

2025-03-02 10:53 UTC, closed without merging